---
title: "ML_Assignment"
output: html_document
---

```{r setup, include = FALSE}

library(dplyr)
library(ggplot2)
library(GGally)
library(corrplot)
library(skimr)
library(knitr)
library(kableExtra)
library(ggparty)
library(rpart)
library(caret)
library(randomForest)

file = "https://raw.githubusercontent.com/ccscaiado/MLRepo/main/Assignment%202%20Datasets/Pokemon/pokemon.csv"

pokemon_data = read.csv(file, header = TRUE)

seed = 1234

```

```{r}

# Check for NAs 
colSums(is.na(pokemon_data))

```

```{r}

# Check column data types 
sapply(pokemon_data, class)

```

```{r}

# Initial data processing 

# Assign height and weight values manually scraped from serebii 
pokemon_data_clean = pokemon_data %>% 
  dplyr::mutate(height_m = case_when(name == "Rattata" ~ 0.3, 
                                     name == "Raticate" ~ 0.7,
                                     name == "Raichu" ~ 0.8,
                                     name == "Sandshrew" ~ 0.6,
                                     name == "Sandslash" ~ 1,
                                     name == "Vulpix" ~ 0.6,
                                     name == "Ninetales" ~ 1.1,
                                     name == "Diglett" ~ 0.2,
                                     name == "Dugtrio" ~ 0.7,
                                     name == "Meowth" ~ 0.4,
                                     name == "Persian" ~ 1,
                                     name == "Geodude" ~ 0.4,
                                     name == "Graveler" ~ 1,
                                     name == "Golem" ~ 1.4,
                                     name == "Grimer" ~ 0.9,
                                     name == "Muk" ~ 1.2,
                                     name == "Exeggutor" ~ 2,
                                     name == "Marowak" ~ 1,
                                     name == "Hoopa" ~ 0.5,
                                     name == "Lycanroc" ~ 0.8, 
                                     TRUE ~ height_m)) %>% 
  dplyr::mutate(weight_kg = case_when(name == "Rattata" ~ 3.5, 
                                     name == "Raticate" ~ 18.5,
                                     name == "Raichu" ~ 30,
                                     name == "Sandshrew" ~ 12,
                                     name == "Sandslash" ~ 29.5,
                                     name == "Vulpix" ~ 9.9,
                                     name == "Ninetales" ~ 19.9,
                                     name == "Diglett" ~ 0.8,
                                     name == "Dugtrio" ~ 33.3,
                                     name == "Meowth" ~ 4.2,
                                     name == "Persian" ~ 32,
                                     name == "Geodude" ~ 20,
                                     name == "Graveler" ~ 105,
                                     name == "Golem" ~ 300,
                                     name == "Grimer" ~ 30,
                                     name == "Muk" ~ 30,
                                     name == "Exeggutor" ~ 120,
                                     name == "Marowak" ~ 45,
                                     name == "Hoopa" ~ 9,
                                     name == "Lycanroc" ~ 25, 
                                     TRUE ~ weight_kg)) %>% 
  dplyr::mutate(alolan_form_exists = case_when(name == "Rattata" ~ 1, 
                                     name == "Raticate" ~ 1,
                                     name == "Raichu" ~ 1,
                                     name == "Sandshrew" ~ 1,
                                     name == "Sandslash" ~ 1,
                                     name == "Vulpix" ~ 1,
                                     name == "Ninetales" ~ 1,
                                     name == "Diglett" ~ 1,
                                     name == "Dugtrio" ~ 1,
                                     name == "Meowth" ~ 1,
                                     name == "Persian" ~ 1,
                                     name == "Geodude" ~ 1,
                                     name == "Graveler" ~ 1,
                                     name == "Golem" ~ 1,
                                     name == "Grimer" ~ 1,
                                     name == "Muk" ~ 1,
                                     name == "Exeggutor" ~ 1,
                                     name == "Marowak" ~ 45,
                                     TRUE ~ 0)) %>% 
  dplyr::mutate(alolan_form_exists = as.factor(alolan_form_exists))

pokemon_data_clean = pokemon_data_clean %>% 
  dplyr::select(-c(abilities, japanese_name, name, pokedex_number, type2)) %>% # Remove unnecessary columns - type2 because of data quality (Kaggle)
  dplyr::mutate(capture_rate = as.numeric(if_else(capture_rate == "30 (Meteorite)255 (Core)", "142.5", capture_rate))) %>% # Fix character issue 
  # Minior has a differing catch rate dependent on form based on if it is above or below 50% hp and therefore the expected value for catch rate is 
  # assumed to be (30 + 255) / 2 = 142.5 
  dplyr::mutate(generation = as.factor(generation)) %>% # Make generation a factor 
  dplyr::mutate(is_legendary = as.factor(is_legendary)) %>% # Make is_legendary a factor 
  dplyr::mutate(type1 = as.factor(type1)) %>% # Make type1 a factor 
  dplyr::rename(classification = classfication) %>% 
  dplyr::mutate(classification = as.factor(classification)) %>% # Make classification a factor 
  dplyr::select(-c(classification)) # TODO: Decide to keep classification or not. Currently removed due to many small classes 
  # Remove classification based on it having too many categories (prohibitively long run time for random forest) 
  # Remove is_legendary based on feature importance being very low and only a very small reduction in accuracy once removed 

```

```{r}

# Working out most appropriate imputation technique - height_m 
hist(pokemon_data_clean$height_m) # Outliers present and not normally distributed therefore median better than mean cause less sensitive to outliers 

```

```{r}

# Working out most appropriate imputation technique - weight_kg 
hist(pokemon_data_clean$weight_kg) # Not normally distributed therefore median better than mean 

```

```{r}

# Working out most appropriate imputation technique - percentage_male 
hist(pokemon_data_clean$percentage_male) # Vast majority of values are 50 therefore mode makes most sense 

```


```{r}

# Impute NA values 
pokemon_data_clean = pokemon_data_clean %>% 
  dplyr::mutate(height_m = if_else(is.na(height_m), median(height_m, na.rm = TRUE), height_m)) %>% # Impute height_m NAs with median 
  dplyr::mutate(weight_kg = if_else(is.na(weight_kg), median(weight_kg, na.rm = TRUE), weight_kg)) %>% # Impute weight_kg NAs with median 
  dplyr::mutate(percentage_male_cat = case_when(is.na(percentage_male) ~ "Genderless", 
                                            percentage_male == 50 ~ "50/50",
                                            percentage_male < 50 ~ "<50",
                                            percentage_male > 50 ~ ">50")) %>% # Categorise percentage male 
  dplyr::mutate(percentage_male_cat = as.factor(percentage_male_cat)) %>% # Make percentage_male_cat a factor 
  dplyr::select(-percentage_male) # Remove percentage_male column 

# TODO: Can manually get specific height and weight values from serebii instead of imputing 

```

```{r}

# Check for any NAs 
any(is.na(pokemon_data_clean))

```

```{r}

# Remove categorical variables 
pokemon_data_pairs = pokemon_data_clean %>% 
  dplyr::select(-c(type1, generation, is_legendary, percentage_male_cat, alolan_form_exists))

# Prepare data 
pokemon_data_pairs_matrix = cor(pokemon_data_pairs)

# Create correlation heatmap 
corrplot(pokemon_data_pairs_matrix, method = "color", type = "upper", order = "hclust",
         tl.col = "black", tl.srt = 90)

# capture_rate is strongly negatively correlated with base_total 
# defense, sp_defense, attack, hp positively correlated with base_total 
# against_ghost negatively correlated with against fight 
# against_dark positively correlated with against_ghost 


```

```{r}

# Create correlation heatmap with coefficients 
corrplot(pokemon_data_pairs_matrix, method = "color", type = "upper", order = "hclust",
         tl.col = "black", tl.srt = 90, addCoef.col = "black", number.cex = 0.5)

```

```{r}

# Summarise dataset 
summary(pokemon_data_clean)

```

```{r}

# Summarise dataset 
skim(pokemon_data_clean)

```

```{r}

# Create subset with only numeric variables 
pokemon_data_clean_numeric = pokemon_data_clean %>% 
  dplyr::select(-c(type1, generation, is_legendary, percentage_male_cat, alolan_form_exists))

# Create numeric variables summary table 
kable(summary(pokemon_data_clean_numeric)) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```

```{r}

# Create subset with only categorical variables 
pokemon_data_clean_categorical = pokemon_data_clean %>% 
  dplyr::select(c(type1, generation, is_legendary, percentage_male_cat, alolan_form_exists))

# Create categorical variables summary table 
kable(summary(pokemon_data_clean_categorical)) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```

```{r}

# Set seed 
set.seed(seed)

# Proportion of data to partition into test split 
test_split = 0.25

# Sample indices based on the test split proportion using stratified random sampling at the type1 level 
# This ensures the test dataset includes a representative proportion of each type1 class from the full dataset 
indices = createDataPartition(pokemon_data_clean$type1, p = test_split, list = FALSE, times = 1)

#indices = sample(1:nrow(pokemon_data_clean), size = round(nrow(pokemon_data_clean) * test_split))

# Create test set 
test_data = pokemon_data_clean[indices,]
# Create training set 
training_data = pokemon_data_clean[-indices,]

```

```{r}

# Define cp values to run for tuning 
tuneGrid = expand.grid(cp = seq(0.001, 0.1, by = 0.001))

# Specify 5-fold cross-validation 
fitControl = trainControl(method = "cv", 
                          number = 5)

# Set seed 
set.seed(seed)

# Perform 5-fold cross-validation 
model_cart = train(type1 ~ .,
                   data = training_data,
                   method = "rpart",
                   tuneGrid = tuneGrid,
                   trControl = fitControl)

plot(as.party(model_cart$finalModel))

print(model_cart)

```

```{r}

# Predict type1 values for test data 
predictions = predict(model_cart, newdata = test_data)
# Print confusion matrix 
confusionMatrix(predictions, test_data$type1)

```

```{r}

# Define mtry values to run for tuning 
tuneGrid = expand.grid(mtry = c(1:((ncol(pokemon_data_clean) / 2) + 1)))

# Specify 5-fold cross-validation 
fitControl = trainControl(method = "cv", 
                          number = 5)

# Set seed 
set.seed(seed)

# Perform 5-fold cross-validation and mtry tuning 
model_rf = train(type1 ~ ., 
                 data = training_data, 
                 method = "rf", 
                 tuneGrid = tuneGrid, 
                 trControl = fitControl, 
                 metric = "Accuracy")

print(model_rf)

```

```{r}

# Predict type1 values for test data 
predictions = predict(model_rf, newdata = test_data)
# Print confusion matrix 
confusionMatrix(predictions, test_data$type1)

```

```{r}

# Best mtry value 
mtry = model_rf$bestTune[[1]]

# Loop through ntrees values and tune 
for (ntrees in c(500, 1000, 1500, 2000)) {
  
  # Set seed 
  set.seed(seed)
  
  # Create model version based on ntrees value 
  model_rf_nt = randomForest(type1 ~ ., data = training_data, ntree = ntrees, mtry = mtry)
  
  # Predict type1 values for test data 
  predictions = predict(model_rf_nt, newdata = test_data)
  
  # Print accuracy for each model version 
  print(round(confusionMatrix(predictions, test_data$type1)$overall[[1]], 2))

}

```

```{r}

# Set seed 
set.seed(seed)

model_rf = randomForest(type1 ~ ., data = training_data, ntree = 500, mtry = mtry)

model_rf

# Assess feature importance 
importance(model_rf)

```

```{r}

# TODO: Collect data for newer generations, test model on newer generations 

```

